### ISSUE TITLE
Page navigation is broken on the search page

### ISSUE THREAD

**Issue by sampaccoud** [openfun/ashley#240]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
On some of our forums, we have thousands of posts.
The search page only displays 20 posts per page and the page per page navigation is impossible because some pages are not accessible:

<img src="https://user-images.githubusercontent.com/1427165/149313824-2e8801b2-39c2-4ed8-b5f7-7dbb5b87aaf3.png" width="200"/>

**Describe the solution you'd like**
- Display much more posts per page
- Fix missing links on pagination

**Describe alternatives you've considered**
Implement infinite scrolling (cf how it was done in Richie https://github.com/openfun/richie/pull/1528/files)

**Comment by carofun** [comment]
arrf...I did the work without reading the issue, getting the info directly from Wendy's return.
Honestly, I think 20 is good enough no?

**Comment by sampaccoud** [comment]
I think we should ship the fix first then ask users what they think.
