### ISSUE TITLE
Group permissions synchronization

### ISSUE THREAD

**Issue by madmatah** [openfun/ashley#91]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**

Ashley permissions for LTI groups are defined with the setting `ASHLEY_DEFAULT_FORUM_ROLES_PERMISSIONS`.
If the set of default permissions is modified, it is only applied to the groups that are created after the setting update and it can lead to inconsistent behavious between forums.

**Describe the solution you'd like**

We would like to synchronize all LTI group permissions each time the `migrate` management command is run.

It can be done with a signal receiver plugged on the `post_migrate` signal.

**Do you want to work on it through a Pull Request?**

Yes !

**Comment by sampaccoud** [comment]
@madmatah can I argue that if you enforce these permissions by overriding what is in db, it is not a default anymore? More like a required permissions?

**Comment by madmatah** [comment]
> @madmatah can I argue that if you enforce these permissions by overriding what is in db, it is not a default anymore? More like a required permissions?

You're right.

And if we sync these permissions, we'll not be able to customize them permanently for a specific group in DB.
I don't know what's the best option...

Maybe, instead of synchronize the permissions between the settings and the DB (by adding the missing permissions and deleting the extra permissions),  we could only add the missing permissions that are defined in the settings but not in DB ? And the settings will reflect the  «required permissions», like you said.

**Comment by sampaccoud** [comment]
What worries me is that it's worse to add again permissions that were removed than to not add permissions that are missing. To me the best option is to only apply the new setting to new accounts and let operators apply specific treatments to existing accounts manually? This could be explained in upgrade instructions?
Manually means that you could provide a script or scripts but it has to be run voluntarily.

**Comment by madmatah** [comment]
Yes, I think i'll provide a management command to synchronize group permissions between DB and the settings.

And we should document it in the upgrade notes when new permissions are added.
